name: dispatch
on:
  push:
  workflow_dispatch:
jobs:
  dispatch:
    name: dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish
          token: ${{ secrets.PUBLISH_SECRET }}
          repo: mdref/mdref
